/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hn.uth.pa1.parcial3.aplicacion;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        ImageIcon imagenicon= new ImageIcon(getClass().getResource("/imagenes/login.jpg"));
        Icon login = new ImageIcon(imagenicon.getImage().getScaledInstance(lblicon.getWidth(), lblicon.getHeight(), Image.SCALE_DEFAULT));
        lblicon.setIcon(login);
        this.repaint();
       
    }

 
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConexion = new javax.swing.JButton();
        lblLogin = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        lbluser = new javax.swing.JLabel();
        lblicon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblversion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gustavo's Proyect");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConexion.setText("Conectar");
        btnConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConexionActionPerformed(evt);
            }
        });
        getContentPane().add(btnConexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        lblLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setText("Menu de Conexion");
        getContentPane().add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 170, 40));
        getContentPane().add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 144, -1));

        lbluser.setForeground(new java.awt.Color(255, 255, 255));
        lbluser.setText("Ingrese el Usuario");
        getContentPane().add(lbluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        lblicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login.jpg"))); // NOI18N
        lblicon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 110, 90));

        jLabel1.setText("Version 1.0.0");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 90, -1));

        lblversion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        lblversion.setText("Verso");
        getContentPane().add(lblversion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 333));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConexionActionPerformed
        // TODO add your handling code here:
        if(txtLogin.getText().equals("uth")){
            JOptionPane.showMessageDialog(null,"Usuario Correcto");
               this.setVisible(false);
               new frmMenu().setVisible(true); 

            ;
        }else{
            JOptionPane.showMessageDialog(null,"usuario no existe.");
            JOptionPane.showMessageDialog(null,"Por favor use 'uth' como  preterminado");
    }//GEN-LAST:event_btnConexionActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConexion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblicon;
    private javax.swing.JLabel lbluser;
    private javax.swing.JLabel lblversion;
    private javax.swing.JTextField txtLogin;
    // End of variables declaration//GEN-END:variables
}
