/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hn.uth.vehiculo.aplicacion;

import hn.uth.vehiculo.aplicacion.objeto.Conexion;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gustavo
 */
public class toyota extends javax.swing.JFrame {

    /**
     * Creates new form toyota
     */
    Conexion con= new Conexion();
    Connection cn= con.getConexion();
    public toyota() {
        initComponents();
        ImageIcon imagenToyota= new ImageIcon(getClass().getResource("/imagen/toyota.PNG"));
        Icon Toyota = new ImageIcon(imagenToyota.getImage().getScaledInstance(lblVistaT.getWidth(), lblVistaT.getHeight(), Image.SCALE_DEFAULT));
        lblVistaT.setIcon(Toyota);
        this.repaint();
        mostrartabla();
        mostrartabla2();
    } void mostrartabla(){
    DefaultTableModel modelo2= new DefaultTableModel();
    modelo2.addColumn("Placa");
    modelo2.addColumn("Modelo");
    modelo2.addColumn("Marca");
    modelo2.addColumn("Anio");
    modelo2.addColumn("Motor");
    modelo2.addColumn("Precio");
    modelo2.addColumn("Nombre");
     modelo2.addColumn("Imagen");
     tblT.setModel(modelo2);
     
     String sql= "Select* from vehiculo WHERE Anio=2018 ";
          
     
     String datos2[] = new String[8];
     Statement st;
     try{
         st= cn.createStatement();
         ResultSet rs=st.executeQuery(sql);
         while(rs.next()){
             datos2[0]= rs.getString(1);
             datos2[1]= rs.getString(2);
             datos2[2]= rs.getString(3);
             datos2[3]= rs.getString(4);
             datos2[4]= rs.getString(5);
             datos2[5]= rs.getString(6);
             datos2[6]= rs.getString(7);
             datos2[7]= rs.getString(8);
            
             modelo2.addRow(datos2);
         }
         tblT.setModel(modelo2);
     }catch(SQLException e){
         }
     }
     void mostrartabla2(){
    DefaultTableModel modelo= new DefaultTableModel();
  
    modelo.addColumn("Descripcion");
   
     w.setModel(modelo);
     
     String sql= "Select Descripcion from vehiculo WHERE Anio=2014 ";
          
     
     String datos[] = new String[1];
     Statement st;
     try{
         st= cn.createStatement();
         ResultSet rs=st.executeQuery(sql);
         while(rs.next()){
             datos[0]= rs.getString(1);
         
             modelo.addRow(datos);
         }
         w.setModel(modelo);
     }catch(SQLException e){
         
     }
  }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloB = new javax.swing.JLabel();
        lblVistaT = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblT = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        w = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTituloB.setText("VISTA VEHICULO");

        lblVistaT.setText("jLabel1");

        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        tblT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblT);

        w.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(w);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(lblTituloB))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btnRegresar)))
                        .addGap(0, 315, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lblVistaT, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(lblVistaT, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnRegresar)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(toyota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(toyota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(toyota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(toyota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new toyota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTituloB;
    private javax.swing.JLabel lblVistaT;
    private javax.swing.JTable tblT;
    private javax.swing.JTable w;
    // End of variables declaration//GEN-END:variables
}
