/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hn.uth.vehiculo.aplicacion;

import hn.uth.vehiculo.aplicacion.objeto.Conexion;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alumno
 */
public class Vehiculos extends javax.swing.JFrame {

    /**
     * Creates new form Vehiculos
     */
     Conexion con= new Conexion();
    Connection cn= con.getConexion();
    public Vehiculos() {
        initComponents();
       ImageIcon imagenBmw= new ImageIcon(getClass().getResource("/imagen/bmw.PNG"));
        Icon BMW = new ImageIcon(imagenBmw.getImage().getScaledInstance(lblBmw.getWidth(), lblBmw.getHeight(), Image.SCALE_DEFAULT));
        lblBmw.setIcon(BMW);
        this.repaint();
        ImageIcon imagenToyota= new ImageIcon(getClass().getResource("/imagen/toyota.PNG"));
        Icon Toyota = new ImageIcon(imagenToyota.getImage().getScaledInstance(lblToyota.getWidth(), lblToyota.getHeight(), Image.SCALE_DEFAULT));
        lblToyota.setIcon(Toyota);
        this.repaint();
        ImageIcon imagenKia= new ImageIcon(getClass().getResource("/imagen/kia.PNG"));
        Icon Kia = new ImageIcon(imagenKia.getImage().getScaledInstance(lblKia.getWidth(), lblKia.getHeight(), Image.SCALE_DEFAULT));
        lblKia.setIcon(Kia);
        this.repaint();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCatalogo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblBmw = new javax.swing.JLabel();
        lblNombreB = new javax.swing.JLabel();
        lblMarcaB = new javax.swing.JLabel();
        lblAnioB = new javax.swing.JLabel();
        lblModeloB = new javax.swing.JLabel();
        lblPrecioB = new javax.swing.JLabel();
        lblMotorB = new javax.swing.JLabel();
        lblPlacaB = new javax.swing.JLabel();
        btnBMW = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblToyota = new javax.swing.JLabel();
        lblNombreT = new javax.swing.JLabel();
        lblMarcaT = new javax.swing.JLabel();
        lblModeloT = new javax.swing.JLabel();
        lblPrecioT = new javax.swing.JLabel();
        lblAnioT = new javax.swing.JLabel();
        lblMotorT = new javax.swing.JLabel();
        lblPlacaT = new javax.swing.JLabel();
        btnToyota = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblKia = new javax.swing.JLabel();
        lblPlacaK = new javax.swing.JLabel();
        lblMotorK = new javax.swing.JLabel();
        lblAnioK = new javax.swing.JLabel();
        lblPrecioK = new javax.swing.JLabel();
        lblModeloK = new javax.swing.JLabel();
        lblMarcaK = new javax.swing.JLabel();
        lblNombreK = new javax.swing.JLabel();
        btnKia = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtfiltro = new javax.swing.JTextField();
        btnfiltro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCatalogo.setText("Catalogo de Vehiculos");

        lblBmw.setText("BMW");

        lblNombreB.setText("Nombre: FAST 1");

        lblMarcaB.setText("Marca: BMW");

        lblAnioB.setText("Año: 2018");

        lblModeloB.setText("Modelo: BMW01");

        lblPrecioB.setText("Precio: LSP 200,000.00");

        lblMotorB.setText("Motor: 2.0");

        lblPlacaB.setText("Placa: PD010");

        btnBMW.setBackground(new java.awt.Color(102, 102, 102));
        btnBMW.setText("VER");
        btnBMW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBMWActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBmw, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNombreB)
                        .addGap(94, 94, 94)
                        .addComponent(lblAnioB)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblModeloB)
                                    .addComponent(lblMarcaB))
                                .addGap(94, 94, 94)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMotorB)
                                    .addComponent(lblPlacaB)))
                            .addComponent(lblPrecioB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBMW, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreB)
                            .addComponent(lblAnioB, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblMarcaB)
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblModeloB)
                                    .addComponent(btnBMW, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblBmw, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPrecioB)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblMotorB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPlacaB, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)))))
                .addGap(4, 4, 4))
        );

        lblToyota.setText("Toyota");

        lblNombreT.setText("Nombre: TOY1");

        lblMarcaT.setText("Marca: Toyota");

        lblModeloT.setText("Modelo: Tacoma");

        lblPrecioT.setText("Precio: LSP 400,000.00");

        lblAnioT.setText("Año: 2014");

        lblMotorT.setText("Motor: 2.0");

        lblPlacaT.setText("Placa: PH025");

        btnToyota.setBackground(new java.awt.Color(102, 102, 102));
        btnToyota.setText("VER");
        btnToyota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToyotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblToyota, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrecioT)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreT)
                            .addComponent(lblMarcaT)
                            .addComponent(lblModeloT))
                        .addGap(96, 96, 96)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPlacaT)
                            .addComponent(lblAnioT)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblMotorT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnToyota, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreT)
                            .addComponent(lblAnioT, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMotorT)
                            .addComponent(btnToyota, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblModeloT, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblToyota, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMarcaT))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPlacaT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrecioT)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        lblKia.setText("Kia");

        lblPlacaK.setText("Placa: PDZ90");

        lblMotorK.setText("Motor: 2.0");

        lblAnioK.setText("Año: 2012");

        lblPrecioK.setText("Precio: LSP 300,000.00");

        lblModeloK.setText("Modelo: Sorento");

        lblMarcaK.setText("Marca: KIA");

        lblNombreK.setText("Nombre: SOR1");

        btnKia.setBackground(new java.awt.Color(102, 102, 102));
        btnKia.setText("VER");
        btnKia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKia, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombreK, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblModeloK)
                                .addComponent(lblMarcaK))
                            .addGap(106, 106, 106)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPlacaK)
                                .addComponent(lblMotorK)
                                .addComponent(lblAnioK)))
                        .addComponent(lblPrecioK)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKia, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblNombreK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMarcaK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblModeloK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPrecioK)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKia, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblAnioK, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMotorK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPlacaK)
                            .addComponent(btnKia, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
        );

        jLabel1.setText("FILTRAR POR AÑO");

        btnfiltro.setBackground(new java.awt.Color(51, 51, 51));
        btnfiltro.setText("Buscar");
        btnfiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfiltroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(btnfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBMWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBMWActionPerformed
         bmw formulario=new bmw();
        formulario
                .setDefaultCloseOperation
                (javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        formulario.setVisible(true);
    }//GEN-LAST:event_btnBMWActionPerformed

    private void btnToyotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToyotaActionPerformed
        toyota formulario=new toyota();
        formulario
                .setDefaultCloseOperation
                (javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        formulario.setVisible(true);
    }//GEN-LAST:event_btnToyotaActionPerformed

    private void btnKiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKiaActionPerformed
        kia formulario=new kia();
        formulario
                .setDefaultCloseOperation
                (javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        formulario.setVisible(true);
    }//GEN-LAST:event_btnKiaActionPerformed

    private void btnfiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfiltroActionPerformed
       try{
           Integer anio=Integer.valueOf(txtfiltro.getText());
           if(anio==2018){
                 bmw formulario=new bmw();
        formulario
                .setDefaultCloseOperation
                (javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        formulario.setVisible(true);
           }
           if(anio==2014){
                 toyota formulario=new toyota();
        formulario
                .setDefaultCloseOperation
                (javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        formulario.setVisible(true);
           }if(anio==2012){
                kia formulario=new kia();
        formulario
                .setDefaultCloseOperation
                (javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        formulario.setVisible(true);
           }else{

           }
           
       }catch(Exception e){
 mostrarMensaje("Error: Año seleccionado no existe en la base de datos ");
          mostrarMensaje("Intente con Otro año");
       }
    }//GEN-LAST:event_btnfiltroActionPerformed

       public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    } 
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vehiculos().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBMW;
    private javax.swing.JButton btnKia;
    private javax.swing.JButton btnToyota;
    private javax.swing.JButton btnfiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAnioB;
    private javax.swing.JLabel lblAnioK;
    private javax.swing.JLabel lblAnioT;
    private javax.swing.JLabel lblBmw;
    private javax.swing.JLabel lblCatalogo;
    private javax.swing.JLabel lblKia;
    private javax.swing.JLabel lblMarcaB;
    private javax.swing.JLabel lblMarcaK;
    private javax.swing.JLabel lblMarcaT;
    private javax.swing.JLabel lblModeloB;
    private javax.swing.JLabel lblModeloK;
    private javax.swing.JLabel lblModeloT;
    private javax.swing.JLabel lblMotorB;
    private javax.swing.JLabel lblMotorK;
    private javax.swing.JLabel lblMotorT;
    private javax.swing.JLabel lblNombreB;
    private javax.swing.JLabel lblNombreK;
    private javax.swing.JLabel lblNombreT;
    private javax.swing.JLabel lblPlacaB;
    private javax.swing.JLabel lblPlacaK;
    private javax.swing.JLabel lblPlacaT;
    private javax.swing.JLabel lblPrecioB;
    private javax.swing.JLabel lblPrecioK;
    private javax.swing.JLabel lblPrecioT;
    private javax.swing.JLabel lblToyota;
    private javax.swing.JTextField txtfiltro;
    // End of variables declaration//GEN-END:variables
}
